---
deployment:
  tasks:
    # Replace 'username' with your cPanel username and 'public_html' with your target directory
    - export DEPLOYPATH=/home/grillpar/public_html/
    
    # Install dependencies and build
    # Ensure Node.js is installed and configured in cPanel
    - /usr/bin/npm install
    - /usr/bin/npm run build
    
    # Copy build artifacts to deployment path
    - /bin/cp -R dist/* $DEPLOYPATH
