---
deployment:
  tasks:
    # Replace 'username' with your cPanel username and 'public_html' with your target directory
    - export DEPLOYPATH=/home/grillpar/public_html/
    
    # Copy build artifacts to deployment path
    # Note: Ensure you run 'npm run build' locally and commit the 'dist' folder
    - /bin/cp -R dist/* $DEPLOYPATH
